export interface lifeExp {
	country: string;
	male: number | null;
	female: number | null;
	overall: number | null;
}
export const lifeExpectancies: lifeExp[] = [
	{ country: 'Japan', male: 84.5, female: 87.5, overall: 81.1 },
	{ country: 'Hong Kong', male: 84.1, female: 87, overall: 81.2 },
	{ country: 'Singapore', male: 83.8, female: 85.8, overall: 81.5 },
	{ country: 'Italy', male: 83.6, female: 85.5, overall: 81.7 },
	{ country: 'Spain', male: 83.4, female: 86.1, overall: 80.7 },
	{ country: 'Switzerland', male: 83.4, female: 85.3, overall: 81.1 },
	{ country: 'Australia', male: 83.3, female: 85.3, overall: 81.3 },
	{ country: 'Iceland', male: 82.9, female: 84.4, overall: 81.3 },
	{ country: 'Israel', male: 82.8, female: 84.4, overall: 81.1 },
	{ country: 'South Korea', male: 82.8, female: 85.8, overall: 79.7 },
	{ country: 'Sweden', male: 82.7, female: 84.4, overall: 80.9 },
	{ country: 'France', male: 82.5, female: 85.4, overall: 79.6 },
	{ country: 'Malta', male: 82.4, female: 84.1, overall: 80.5 },
	{ country: 'Canada', male: 82.3, female: 84.3, overall: 80.3 },
	{ country: 'Norway', male: 82.3, female: 84.3, overall: 80.3 },
	{ country: 'Greece', male: 82.1, female: 84.5, overall: 79.6 },
	{ country: 'Ireland', male: 82.1, female: 83.7, overall: 80.4 },
	{ country: 'Luxembourg', male: 82.1, female: 84.2, overall: 80 },
	{ country: 'Netherlands', male: 82.1, female: 83.8, overall: 80.4 },
	{ country: 'New Zealand', male: 82.1, female: 83.9, overall: 80.4 },
	{ country: 'Portugal', male: 81.9, female: 84.7, overall: 78.8 },
	{ country: 'Andorra', male: 81.8, female: null, overall: null },
	{ country: 'Finland', male: 81.7, female: 84.6, overall: 78.9 },
	{
		country: 'Saint Helena, Ascension and Tristan da Cunha',
		male: 81.5,
		female: 83.8,
		overall: 79.1,
	},
	{ country: 'Belgium', male: 81.5, female: 83.8, overall: 79.1 },
	{ country: 'Austria', male: 81.4, female: 83.8, overall: 79 },
	{ country: 'Germany', male: 81.2, female: 83.6, overall: 78.8 },
	{ country: 'Slovenia', male: 81.2, female: 83.9, overall: 78.4 },
	{ country: 'United Kingdom', male: 81.2, female: 83, overall: 79.5 },
	{ country: 'Cyprus', male: 80.8, female: 82.9, overall: 78.7 },
	{ country: 'Denmark', male: 80.8, female: 82.8, overall: 77.8 },
	{ country: 'Liechtenstein', male: 80.5, female: null, overall: null },
	{ country: 'Costa Rica', male: 80.1, female: 82.7, overall: 77.5 },
	{ country: 'Chile', male: 80, female: 82.4, overall: 77.6 },
	{ country: 'Czech Republic', male: 79.2, female: 81.8, overall: 76.6 },
	{ country: 'Barbados', male: 79.1, female: 80.4, overall: 77.7 },
	{ country: 'Lebanon', male: 78.9, female: 80.8, overall: 77.1 },
	{ country: 'United States of America', male: 78.9, female: 81.4, overall: 76.3 },
	{ country: 'Cuba', male: 78.6, female: 80.6, overall: 76.7 },
	{ country: 'Estonia', male: 78.6, female: 82.4, overall: 73.9 },
	{ country: 'Poland', male: 78.5, female: 82.4, overall: 74.6 },
	{ country: 'Croatia', male: 78.3, female: 81.5, overall: 75.1 },
	{ country: 'Panama', male: 78.3, female: 81.6, overall: 75.2 },
	{ country: 'Turkey', male: 78.3, female: 81, overall: 75.6 },
	{ country: 'United Arab Emirates', male: 77.8, female: 79.2, overall: 77.1 },
	{ country: 'Uruguay', male: 77.8, female: 81.4, overall: 74 },
	{ country: 'Oman', male: 77.6, female: 80.1, overall: 75.9 },
	{ country: 'Slovakia', male: 77.4, female: 80.8, overall: 73.8 },
	{ country: 'Bosnia and Herzegovina', male: 77.3, female: 79.7, overall: 74.8 },
	{ country: 'Bahrain', male: 77.2, female: 78.3, overall: 76.3 },
	{ country: 'Colombia', male: 77.1, female: 79.9, overall: 74.3 },
	{ country: 'Antigua and Barbuda', male: 76.9, female: 78, overall: 75.7 },
	{ country: 'Thailand', male: 76.9, female: 80.7, overall: 73.2 },
	{ country: 'Ecuador', male: 76.8, female: 79.6, overall: 74.1 },
	{ country: 'Montenegro', male: 76.8, female: 79.2, overall: 74.3 },
	{ country: 'Sri Lanka', male: 76.8, female: 80.1, overall: 73.4 },
	{ country: 'Algeria', male: 76.7, female: 77.9, overall: 75.5 },
	{ country: 'Hungary', male: 76.7, female: 80.1, overall: 73.1 },
	{ country: 'China', male: 76.7, female: 79.1, overall: 74.5 },
	{ country: 'Argentina', male: 76.5, female: 79.9, overall: 73.1 },
	{ country: 'Iran', male: 76.5, female: 77.7, overall: 75.4 },
	{ country: 'Morocco', male: 76.5, female: 77.7, overall: 75.2 },
	{ country: 'Peru', male: 76.5, female: 79.3, overall: 73.8 },
	{ country: 'Tunisia', male: 76.5, female: 78.5, overall: 74.5 },
	{ country: 'Malaysia', male: 76.1, female: 78.3, overall: 74.2 },
	{ country: 'Saint Lucia', male: 76.1, female: 77.4, overall: 74.7 },
	{ country: 'Romania', male: 75.9, female: 79.4, overall: 72.5 },
	{ country: 'Serbia', male: 75.8, female: 78.5, overall: 73.3 },
	{ country: 'Brazil', male: 75.7, female: 79.4, overall: 72 },
	{ country: 'Brunei', male: 75.7, female: 77, overall: 74.6 },
	{ country: 'Lithuania', male: 75.7, female: 81.2, overall: 70.1 },
	{ country: 'Republic of North Macedonia', male: 75.7, female: 77.7, overall: 73.7 },
	{ country: 'Kuwait', male: 75.4, female: 76.5, overall: 74.7 },
	{ country: 'Vietnam', male: 75.3, female: 79.4, overall: 71.2 },
	{ country: 'Latvia', male: 75.2, female: 79.9, overall: 70.1 },
	{ country: 'Honduras', male: 75.1, female: 77.4, overall: 72.8 },
	{ country: 'Mexico', male: 75, female: 77.8, overall: 72.1 },
	{ country: 'Saudi Arabia', male: 75, female: 76.6, overall: 73.8 },
	{ country: 'Armenia', male: 74.9, female: 78.4, overall: 71.2 },
	{ country: 'Bulgaria', male: 74.9, female: 78.5, overall: 71.4 },
	{ country: 'Mauritius', male: 74.9, female: 78.4, overall: 71.5 },
	{ country: 'Belarus', male: 74.6, female: 79.4, overall: 69.4 },
	{ country: 'Saint Kitts and Nevis', male: 74.6, female: null, overall: null },
	{ country: 'Belize', male: 74.5, female: 77.7, overall: 71.6 },
	{ country: 'Jamaica', male: 74.4, female: 76, overall: 72.8 },
	{ country: 'Jordan', male: 74.4, female: 76.2, overall: 72.7 },
	{ country: 'Nicaragua', male: 74.3, female: 77.8, overall: 70.7 },
	{ country: 'Guatemala', male: 74.1, female: 76.9, overall: 71.1 },
	{ country: 'Paraguay', male: 74.1, female: 76.3, overall: 72.2 },
	{ country: 'Dominican Republic', male: 73.9, female: 77.2, overall: 70.8 },
	{ country: 'Marshall Islands', male: 73.9, female: null, overall: null },
	{ country: 'Palestine', male: 73.9, female: 75.6, overall: 72.3 },
	{ country: 'Bahamas', male: 73.8, female: 75.9, overall: 71.5 },
	{ country: 'Palau', male: 73.7, female: null, overall: null },
	{ country: 'Georgia', male: 73.6, female: 78, overall: 69.2 },
	{ country: 'Trinidad and Tobago', male: 73.4, female: 76.1, overall: 70.8 },
	{ country: 'Seychelles', male: 73.3, female: 77.3, overall: 69.8 },
	{ country: 'Kazakhstan', male: 76.2, female: 77.3, overall: 68.8 },
	{ country: 'Samoa', male: 73.2, female: 75.3, overall: 71.2 },
	{ country: 'El Salvador', male: 73.1, female: 77.6, overall: 68.2 },
	{ country: 'Azerbaijan', male: 72.9, female: 75.3, overall: 70.3 },
	{ country: 'Cabo Verde', male: 72.8, female: 76, overall: 69.3 },
	{ country: 'Solomon Islands', male: 72.8, female: 74.7, overall: 71.2 },
	{ country: 'Libya', male: 72.7, female: 75.8, overall: 69.9 },
	{ country: 'World', male: 72.6, female: 74.9, overall: 70.4 },
	{ country: 'Grenada', male: 72.4, female: 74.9, overall: 70.1 },
	{ country: 'Russia', male: 72.4, female: 77.6, overall: 66.9 },
	{ country: 'Saint Vincent and the Grenadines', male: 72.4, female: 75, overall: 70.2 },
	{ country: 'Bangladesh', male: 72.3, female: 74.3, overall: 70.6 },
	{ country: 'Venezuela', male: 72.1, female: 76.1, overall: 68.4 },
	{ country: 'Ukraine', male: 72, female: 76.7, overall: 67 },
	{ country: 'Egypt', male: 71.8, female: 74.2, overall: 69.6 },
	{ country: 'Moldova', male: 71.8, female: 76.1, overall: 67.5 },
	{ country: 'Syria', male: 71.8, female: 77.8, overall: 66.6 },
	{ country: 'Suriname', male: 71.6, female: 74.9, overall: 68.4 },
	{ country: 'Uzbekistan', male: 74.6, female: 73.7, overall: 69.4 },
	{ country: 'Bhutan', male: 71.5, female: 71.8, overall: 71.1 },
	{ country: 'Indonesia', male: 71.5, female: 73.7, overall: 69.4 },
	{ country: 'Kyrgyzstan', male: 71.3, female: 75.5, overall: 67.3 },
	{ country: 'Bolivia', male: 71.2, female: 74.2, overall: 68.4 },
	{ country: 'Philippines', male: 71.1, female: 75.4, overall: 67.1 },
	{ country: 'Tajikistan', male: 70.9, female: 73.2, overall: 68.7 },
	{ country: 'Tonga', male: 70.8, female: 72.8, overall: 68.9 },
	{ country: 'Iraq', male: 70.5, female: 72.5, overall: 68.4 },
	{ country: 'Nepal', male: 70.5, female: 71.9, overall: 69 },
	{ country: 'Vanuatu', male: 70.3, female: 72, overall: 68.8 },
	{ country: 'Sao Tome and Principe', male: 70.2, female: 72.6, overall: 67.8 },
	{ country: 'Guyana', male: 69.8, female: 73, overall: 66.8 },
	{ country: 'Mongolia', male: 69.7, female: 74, overall: 65.6 },
	{ country: 'Cambodia', male: 69.6, female: 71.6, overall: 67.3 },
	{ country: 'India', male: 69.4, female: 70.7, overall: 68.2 },
	{ country: 'Botswana', male: 69.3, female: 72, overall: 66.2 },
	{ country: 'Timor Leste', male: 69.3, female: 71.4, overall: 67.3 },
	{ country: 'Rwanda', male: 68.7, female: 70.8, overall: 66.5 },
	{ country: 'Kiribati', male: 68.1, female: 72.1, overall: 64 },
	{ country: 'Turkmenistan', male: 68.1, female: 71.6, overall: 64.6 },
	{ country: 'Micronesia', male: 67.8, female: 69.5, overall: 66.1 },
	{ country: 'Senegal', male: 67.7, female: 69.6, overall: 65.5 },
	{ country: 'Laos', male: 67.6, female: 69.4, overall: 65.8 },
	{ country: 'Fiji', male: 67.3, female: 69.2, overall: 65.6 },
	{ country: 'Pakistan', male: 67.1, female: 68.1, overall: 66.2 },
	{ country: 'Myanmar', male: 66.9, female: 69.9, overall: 63.8 },
	{ country: 'Madagascar', male: 66.7, female: 68.3, overall: 65.1 },
	{ country: 'Djibouti', male: 66.6, female: 68.8, overall: 64.6 },
	{ country: 'Ethiopia', male: 66.2, female: 68.2, overall: 64.4 },
	{ country: 'Gabon', male: 66.2, female: 68.9, overall: 64.2 },
	{ country: 'Yemen', male: 66.1, female: 67.8, overall: 64.4 },
	{ country: 'Eritrea', male: 65.9, female: 68.2, overall: 63.8 },
	{ country: 'Sudan', male: 65.1, female: 66.9, overall: 63.3 },
	{ country: 'Tanzania', male: 65, female: 66.8, overall: 63.2 },
	{ country: 'Mauritania', male: 64.7, female: 66.3, overall: 63.1 },
	{ country: 'Afghanistan', male: 64.5, female: 66, overall: 63 },
	{ country: 'Congo', male: 64.3, female: 65.7, overall: 62.8 },
	{ country: 'Papua New Guinea', male: 64.3, female: 65.6, overall: 63 },
	{ country: 'Comoros', male: 64.1, female: 65.9, overall: 62.4 },
	{ country: 'South Africa', male: 63.9, female: 67.4, overall: 60.5 },
	{ country: 'Ghana', male: 63.8, female: 64.9, overall: 62.7 },
	{ country: 'Malawi', male: 63.8, female: 66.9, overall: 60.7 },
	{ country: 'Haiti', male: 63.7, female: 65.8, overall: 61.5 },
	{ country: 'Liberia', male: 63.7, female: 65.1, overall: 62.3 },
	{ country: 'Zambia', male: 63.5, female: 66.4, overall: 60.5 },
	{ country: 'Namibia', male: 63.4, female: 66.2, overall: 60.4 },
	{ country: 'Kenya', male: 63.3, female: 68.7, overall: 64 },
	{ country: 'Uganda', male: 63, female: 65.2, overall: 60.7 },
	{ country: 'Niger', male: 62, female: 63.2, overall: 60.9 },
	{ country: 'Gambia', male: 61.7, female: 63.2, overall: 60.4 },
	{ country: 'Benin', male: 61.5, female: 63, overall: 59.9 },
	{ country: 'Burkina Faso', male: 61.2, female: 61.9, overall: 60.4 },
	{ country: 'Burundi', male: 61.2, female: 63, overall: 59.4 },
	{ country: 'Guinea', male: 61.2, female: 61.7, overall: 60.5 },
	{ country: 'Zimbabwe', male: 61.2, female: 62.6, overall: 59.5 },
	{ country: 'Angola', male: 60.8, female: 63.7, overall: 58.1 },
	{ country: 'Togo', male: 60.8, female: 61.6, overall: 59.9 },
	{ country: 'Congo (the Democratic Republic of the)', male: 60.4, female: 61.9, overall: 58.9 },
	{ country: 'Mozambique', male: 60.2, female: 63, overall: 57.1 },
	{ country: 'Eswatini', male: 59.4, female: 64, overall: 55.3 },
	{ country: 'Cameroon', male: 58.9, female: 60.2, overall: 57.7 },
	{ country: 'Mali', male: 58.9, female: 59.6, overall: 58.1 },
	{ country: 'Equatorial Guinea', male: 58.4, female: 59.6, overall: 57.4 },
	{ country: 'Guinea-Bissau', male: 58, female: 59.9, overall: 56 },
	{ country: 'South Sudan', male: 57.6, female: 59.1, overall: 56.1 },
	{ country: "Côte d'Ivoire", male: 57.4, female: 58.7, overall: 56.3 },
	{ country: 'Nigeria', male: 54.3, female: 55.2, overall: 53.5 },
	{ country: 'Sierra Leone', male: 54.3, female: 55.1, overall: 53.5 },
	{ country: 'Chad', male: 54, female: 55.4, overall: 52.6 },
	{ country: 'Lesotho', male: 53.7, female: 57, overall: 50.6 },
	{ country: 'Central African Republic', male: 52.8, female: 55, overall: 50.6 },
];
export interface Country {
	country: string;
	alpha2: string;
	alpha3: string;
	numeric: number;
	male: number | null;
	female: number | null;
	overall: number | null;
}
export const countryList: Country[] = [
	{
		country: 'Afghanistan',
		alpha2: 'AF',
		alpha3: 'AFG',
		numeric: 4,
		male: 64.5,
		female: 66,
		overall: 63,
	},
	{
		country: 'Albania',
		alpha2: 'AL',
		alpha3: 'ALB',
		numeric: 8,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Algeria',
		alpha2: 'DZ',
		alpha3: 'DZA',
		numeric: 12,
		male: 76.7,
		female: 77.9,
		overall: 75.5,
	},
	{
		country: 'American Samoa',
		alpha2: 'AS',
		alpha3: 'ASM',
		numeric: 16,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Andorra',
		alpha2: 'AD',
		alpha3: 'AND',
		numeric: 20,
		male: 81.8,
		female: null,
		overall: null,
	},
	{
		country: 'Angola',
		alpha2: 'AO',
		alpha3: 'AGO',
		numeric: 24,
		male: 60.8,
		female: 63.7,
		overall: 58.1,
	},
	{
		country: 'Anguilla',
		alpha2: 'AI',
		alpha3: 'AIA',
		numeric: 660,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Antarctica',
		alpha2: 'AQ',
		alpha3: 'ATA',
		numeric: 10,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Antigua and Barbuda',
		alpha2: 'AG',
		alpha3: 'ATG',
		numeric: 28,
		male: 76.9,
		female: 78,
		overall: 75.7,
	},
	{
		country: 'Argentina',
		alpha2: 'AR',
		alpha3: 'ARG',
		numeric: 32,
		male: 76.5,
		female: 79.9,
		overall: 73.1,
	},
	{
		country: 'Armenia',
		alpha2: 'AM',
		alpha3: 'ARM',
		numeric: 51,
		male: 74.9,
		female: 78.4,
		overall: 71.2,
	},
	{
		country: 'Aruba',
		alpha2: 'AW',
		alpha3: 'ABW',
		numeric: 533,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Australia',
		alpha2: 'AU',
		alpha3: 'AUS',
		numeric: 36,
		male: 83.3,
		female: 85.3,
		overall: 81.3,
	},
	{
		country: 'Austria',
		alpha2: 'AT',
		alpha3: 'AUT',
		numeric: 40,
		male: 81.4,
		female: 83.8,
		overall: 79,
	},
	{
		country: 'Azerbaijan',
		alpha2: 'AZ',
		alpha3: 'AZE',
		numeric: 31,
		male: 72.9,
		female: 75.3,
		overall: 70.3,
	},
	{
		country: 'Bahamas',
		alpha2: 'BS',
		alpha3: 'BHS',
		numeric: 44,
		male: 73.8,
		female: 75.9,
		overall: 71.5,
	},
	{
		country: 'Bahrain',
		alpha2: 'BH',
		alpha3: 'BHR',
		numeric: 48,
		male: 77.2,
		female: 78.3,
		overall: 76.3,
	},
	{
		country: 'Bangladesh',
		alpha2: 'BD',
		alpha3: 'BGD',
		numeric: 50,
		male: 72.3,
		female: 74.3,
		overall: 70.6,
	},
	{
		country: 'Barbados',
		alpha2: 'BB',
		alpha3: 'BRB',
		numeric: 52,
		male: 79.1,
		female: 80.4,
		overall: 77.7,
	},
	{
		country: 'Belarus',
		alpha2: 'BY',
		alpha3: 'BLR',
		numeric: 112,
		male: 74.6,
		female: 79.4,
		overall: 69.4,
	},
	{
		country: 'Belgium',
		alpha2: 'BE',
		alpha3: 'BEL',
		numeric: 56,
		male: 81.5,
		female: 83.8,
		overall: 79.1,
	},
	{
		country: 'Belize',
		alpha2: 'BZ',
		alpha3: 'BLZ',
		numeric: 84,
		male: 74.5,
		female: 77.7,
		overall: 71.6,
	},
	{
		country: 'Benin',
		alpha2: 'BJ',
		alpha3: 'BEN',
		numeric: 204,
		male: 61.5,
		female: 63,
		overall: 59.9,
	},
	{
		country: 'Bermuda',
		alpha2: 'BM',
		alpha3: 'BMU',
		numeric: 60,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Bhutan',
		alpha2: 'BT',
		alpha3: 'BTN',
		numeric: 64,
		male: 71.5,
		female: 71.8,
		overall: 71.1,
	},
	{
		country: 'Bolivia',
		alpha2: 'BO',
		alpha3: 'BOL',
		numeric: 68,
		male: 71.2,
		female: 74.2,
		overall: 68.4,
	},
	{
		country: 'Bonaire, Sint Eustatius and Saba',
		alpha2: 'BQ',
		alpha3: 'BES',
		numeric: 535,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Bosnia and Herzegovina',
		alpha2: 'BA',
		alpha3: 'BIH',
		numeric: 70,
		male: 77.3,
		female: 79.7,
		overall: 74.8,
	},
	{
		country: 'Botswana',
		alpha2: 'BW',
		alpha3: 'BWA',
		numeric: 72,
		male: 69.3,
		female: 72,
		overall: 66.2,
	},
	{
		country: 'Bouvet Island',
		alpha2: 'BV',
		alpha3: 'BVT',
		numeric: 74,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Brazil',
		alpha2: 'BR',
		alpha3: 'BRA',
		numeric: 76,
		male: 75.7,
		female: 79.4,
		overall: 72,
	},
	{
		country: 'British Indian Ocean Territory',
		alpha2: 'IO',
		alpha3: 'IOT',
		numeric: 86,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Brunei',
		alpha2: 'BN',
		alpha3: 'BRN',
		numeric: 96,
		male: 75.7,
		female: 77,
		overall: 74.6,
	},
	{
		country: 'Bulgaria',
		alpha2: 'BG',
		alpha3: 'BGR',
		numeric: 100,
		male: 74.9,
		female: 78.5,
		overall: 71.4,
	},
	{
		country: 'Burkina Faso',
		alpha2: 'BF',
		alpha3: 'BFA',
		numeric: 854,
		male: 61.2,
		female: 61.9,
		overall: 60.4,
	},
	{
		country: 'Burundi',
		alpha2: 'BI',
		alpha3: 'BDI',
		numeric: 108,
		male: 61.2,
		female: 63,
		overall: 59.4,
	},
	{
		country: 'Cabo Verde',
		alpha2: 'CV',
		alpha3: 'CPV',
		numeric: 132,
		male: 72.8,
		female: 76,
		overall: 69.3,
	},
	{
		country: 'Cambodia',
		alpha2: 'KH',
		alpha3: 'KHM',
		numeric: 116,
		male: 69.6,
		female: 71.6,
		overall: 67.3,
	},
	{
		country: 'Cameroon',
		alpha2: 'CM',
		alpha3: 'CMR',
		numeric: 120,
		male: 58.9,
		female: 60.2,
		overall: 57.7,
	},
	{
		country: 'Canada',
		alpha2: 'CA',
		alpha3: 'CAN',
		numeric: 124,
		male: 82.3,
		female: 84.3,
		overall: 80.3,
	},
	{
		country: 'Cayman Islands',
		alpha2: 'KY',
		alpha3: 'CYM',
		numeric: 136,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Central African Republic',
		alpha2: 'CF',
		alpha3: 'CAF',
		numeric: 140,
		male: 52.8,
		female: 55,
		overall: 50.6,
	},
	{
		country: 'Chad',
		alpha2: 'TD',
		alpha3: 'TCD',
		numeric: 148,
		male: 54,
		female: 55.4,
		overall: 52.6,
	},
	{
		country: 'Chile',
		alpha2: 'CL',
		alpha3: 'CHL',
		numeric: 152,
		male: 80,
		female: 82.4,
		overall: 77.6,
	},
	{
		country: 'China',
		alpha2: 'CN',
		alpha3: 'CHN',
		numeric: 156,
		male: 76.7,
		female: 79.1,
		overall: 74.5,
	},
	{
		country: 'Christmas Island',
		alpha2: 'CX',
		alpha3: 'CXR',
		numeric: 162,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Cocos (Keeling) Islands',
		alpha2: 'CC',
		alpha3: 'CCK',
		numeric: 166,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Colombia',
		alpha2: 'CO',
		alpha3: 'COL',
		numeric: 170,
		male: 77.1,
		female: 79.9,
		overall: 74.3,
	},
	{
		country: 'Comoros',
		alpha2: 'KM',
		alpha3: 'COM',
		numeric: 174,
		male: 64.1,
		female: 65.9,
		overall: 62.4,
	},
	{
		country: 'Congo (the Democratic Republic of the)',
		alpha2: 'CD',
		alpha3: 'COD',
		numeric: 180,
		male: 60.4,
		female: 61.9,
		overall: 58.9,
	},
	{
		country: 'Congo',
		alpha2: 'CG',
		alpha3: 'COG',
		numeric: 178,
		male: 64.3,
		female: 65.7,
		overall: 62.8,
	},
	{
		country: 'Cook Islands',
		alpha2: 'CK',
		alpha3: 'COK',
		numeric: 184,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Costa Rica',
		alpha2: 'CR',
		alpha3: 'CRI',
		numeric: 188,
		male: 80.1,
		female: 82.7,
		overall: 77.5,
	},
	{
		country: 'Croatia',
		alpha2: 'HR',
		alpha3: 'HRV',
		numeric: 191,
		male: 78.3,
		female: 81.5,
		overall: 75.1,
	},
	{
		country: 'Cuba',
		alpha2: 'CU',
		alpha3: 'CUB',
		numeric: 192,
		male: 78.6,
		female: 80.6,
		overall: 76.7,
	},
	{
		country: 'Curaçao',
		alpha2: 'CW',
		alpha3: 'CUW',
		numeric: 531,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Cyprus',
		alpha2: 'CY',
		alpha3: 'CYP',
		numeric: 196,
		male: 80.8,
		female: 82.9,
		overall: 78.7,
	},
	{
		country: 'Czech Republic',
		alpha2: 'CZ',
		alpha3: 'CZE',
		numeric: 203,
		male: 79.2,
		female: 81.8,
		overall: 76.6,
	},
	{
		country: "Côte d'Ivoire",
		alpha2: 'CI',
		alpha3: 'CIV',
		numeric: 384,
		male: 57.4,
		female: 58.7,
		overall: 56.3,
	},
	{
		country: 'Denmark',
		alpha2: 'DK',
		alpha3: 'DNK',
		numeric: 208,
		male: 80.8,
		female: 82.8,
		overall: 77.8,
	},
	{
		country: 'Djibouti',
		alpha2: 'DJ',
		alpha3: 'DJI',
		numeric: 262,
		male: 66.6,
		female: 68.8,
		overall: 64.6,
	},
	{
		country: 'Dominica',
		alpha2: 'DM',
		alpha3: 'DMA',
		numeric: 212,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Dominican Republic',
		alpha2: 'DO',
		alpha3: 'DOM',
		numeric: 214,
		male: 73.9,
		female: 77.2,
		overall: 70.8,
	},
	{
		country: 'Ecuador',
		alpha2: 'EC',
		alpha3: 'ECU',
		numeric: 218,
		male: 76.8,
		female: 79.6,
		overall: 74.1,
	},
	{
		country: 'Egypt',
		alpha2: 'EG',
		alpha3: 'EGY',
		numeric: 818,
		male: 71.8,
		female: 74.2,
		overall: 69.6,
	},
	{
		country: 'El Salvador',
		alpha2: 'SV',
		alpha3: 'SLV',
		numeric: 222,
		male: 73.1,
		female: 77.6,
		overall: 68.2,
	},
	{
		country: 'Equatorial Guinea',
		alpha2: 'GQ',
		alpha3: 'GNQ',
		numeric: 226,
		male: 58.4,
		female: 59.6,
		overall: 57.4,
	},
	{
		country: 'Eritrea',
		alpha2: 'ER',
		alpha3: 'ERI',
		numeric: 232,
		male: 65.9,
		female: 68.2,
		overall: 63.8,
	},
	{
		country: 'Estonia',
		alpha2: 'EE',
		alpha3: 'EST',
		numeric: 233,
		male: 78.6,
		female: 82.4,
		overall: 73.9,
	},
	{
		country: 'Eswatini',
		alpha2: 'SZ',
		alpha3: 'SWZ',
		numeric: 748,
		male: 59.4,
		female: 64,
		overall: 55.3,
	},
	{
		country: 'Ethiopia',
		alpha2: 'ET',
		alpha3: 'ETH',
		numeric: 231,
		male: 66.2,
		female: 68.2,
		overall: 64.4,
	},
	{
		country: 'Falkland Islands [Malvinas]',
		alpha2: 'FK',
		alpha3: 'FLK',
		numeric: 238,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Faroe Islands',
		alpha2: 'FO',
		alpha3: 'FRO',
		numeric: 234,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Fiji',
		alpha2: 'FJ',
		alpha3: 'FJI',
		numeric: 242,
		male: 67.3,
		female: 69.2,
		overall: 65.6,
	},
	{
		country: 'Finland',
		alpha2: 'FI',
		alpha3: 'FIN',
		numeric: 246,
		male: 81.7,
		female: 84.6,
		overall: 78.9,
	},
	{
		country: 'France',
		alpha2: 'FR',
		alpha3: 'FRA',
		numeric: 250,
		male: 82.5,
		female: 85.4,
		overall: 79.6,
	},
	{
		country: 'French Guiana',
		alpha2: 'GF',
		alpha3: 'GUF',
		numeric: 254,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'French Polynesia',
		alpha2: 'PF',
		alpha3: 'PYF',
		numeric: 258,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'French Southern Territories',
		alpha2: 'TF',
		alpha3: 'ATF',
		numeric: 260,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Gabon',
		alpha2: 'GA',
		alpha3: 'GAB',
		numeric: 266,
		male: 66.2,
		female: 68.9,
		overall: 64.2,
	},
	{
		country: 'Gambia',
		alpha2: 'GM',
		alpha3: 'GMB',
		numeric: 270,
		male: 61.7,
		female: 63.2,
		overall: 60.4,
	},
	{
		country: 'Georgia',
		alpha2: 'GE',
		alpha3: 'GEO',
		numeric: 268,
		male: 73.6,
		female: 78,
		overall: 69.2,
	},
	{
		country: 'Germany',
		alpha2: 'DE',
		alpha3: 'DEU',
		numeric: 276,
		male: 81.2,
		female: 83.6,
		overall: 78.8,
	},
	{
		country: 'Ghana',
		alpha2: 'GH',
		alpha3: 'GHA',
		numeric: 288,
		male: 63.8,
		female: 64.9,
		overall: 62.7,
	},
	{
		country: 'Gibraltar',
		alpha2: 'GI',
		alpha3: 'GIB',
		numeric: 292,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Greece',
		alpha2: 'GR',
		alpha3: 'GRC',
		numeric: 300,
		male: 82.1,
		female: 84.5,
		overall: 79.6,
	},
	{
		country: 'Greenland',
		alpha2: 'GL',
		alpha3: 'GRL',
		numeric: 304,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Grenada',
		alpha2: 'GD',
		alpha3: 'GRD',
		numeric: 308,
		male: 72.4,
		female: 74.9,
		overall: 70.1,
	},
	{
		country: 'Guadeloupe',
		alpha2: 'GP',
		alpha3: 'GLP',
		numeric: 312,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Guam',
		alpha2: 'GU',
		alpha3: 'GUM',
		numeric: 316,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Guatemala',
		alpha2: 'GT',
		alpha3: 'GTM',
		numeric: 320,
		male: 74.1,
		female: 76.9,
		overall: 71.1,
	},
	{
		country: 'Guernsey',
		alpha2: 'GG',
		alpha3: 'GGY',
		numeric: 831,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Guinea',
		alpha2: 'GN',
		alpha3: 'GIN',
		numeric: 324,
		male: 61.2,
		female: 61.7,
		overall: 60.5,
	},
	{
		country: 'Guinea-Bissau',
		alpha2: 'GW',
		alpha3: 'GNB',
		numeric: 624,
		male: 58,
		female: 59.9,
		overall: 56,
	},
	{
		country: 'Guyana',
		alpha2: 'GY',
		alpha3: 'GUY',
		numeric: 328,
		male: 69.8,
		female: 73,
		overall: 66.8,
	},
	{
		country: 'Haiti',
		alpha2: 'HT',
		alpha3: 'HTI',
		numeric: 332,
		male: 63.7,
		female: 65.8,
		overall: 61.5,
	},
	{
		country: 'Heard Island and McDonald Islands',
		alpha2: 'HM',
		alpha3: 'HMD',
		numeric: 334,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Holy See',
		alpha2: 'VA',
		alpha3: 'VAT',
		numeric: 336,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Honduras',
		alpha2: 'HN',
		alpha3: 'HND',
		numeric: 340,
		male: 75.1,
		female: 77.4,
		overall: 72.8,
	},
	{
		country: 'Hong Kong',
		alpha2: 'HK',
		alpha3: 'HKG',
		numeric: 344,
		male: 84.1,
		female: 87,
		overall: 81.2,
	},
	{
		country: 'Hungary',
		alpha2: 'HU',
		alpha3: 'HUN',
		numeric: 348,
		male: 76.7,
		female: 80.1,
		overall: 73.1,
	},
	{
		country: 'Iceland',
		alpha2: 'IS',
		alpha3: 'ISL',
		numeric: 352,
		male: 82.9,
		female: 84.4,
		overall: 81.3,
	},
	{
		country: 'India',
		alpha2: 'IN',
		alpha3: 'IND',
		numeric: 356,
		male: 69.4,
		female: 70.7,
		overall: 68.2,
	},
	{
		country: 'Indonesia',
		alpha2: 'ID',
		alpha3: 'IDN',
		numeric: 360,
		male: 71.5,
		female: 73.7,
		overall: 69.4,
	},
	{
		country: 'Iran',
		alpha2: 'IR',
		alpha3: 'IRN',
		numeric: 364,
		male: 76.5,
		female: 77.7,
		overall: 75.4,
	},
	{
		country: 'Iraq',
		alpha2: 'IQ',
		alpha3: 'IRQ',
		numeric: 368,
		male: 70.5,
		female: 72.5,
		overall: 68.4,
	},
	{
		country: 'Ireland',
		alpha2: 'IE',
		alpha3: 'IRL',
		numeric: 372,
		male: 82.1,
		female: 83.7,
		overall: 80.4,
	},
	{
		country: 'Isle of Man',
		alpha2: 'IM',
		alpha3: 'IMN',
		numeric: 833,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Israel',
		alpha2: 'IL',
		alpha3: 'ISR',
		numeric: 376,
		male: 82.8,
		female: 84.4,
		overall: 81.1,
	},
	{
		country: 'Italy',
		alpha2: 'IT',
		alpha3: 'ITA',
		numeric: 380,
		male: 83.6,
		female: 85.5,
		overall: 81.7,
	},
	{
		country: 'Jamaica',
		alpha2: 'JM',
		alpha3: 'JAM',
		numeric: 388,
		male: 74.4,
		female: 76,
		overall: 72.8,
	},
	{
		country: 'Japan',
		alpha2: 'JP',
		alpha3: 'JPN',
		numeric: 392,
		male: 84.5,
		female: 87.5,
		overall: 81.1,
	},
	{
		country: 'Jersey',
		alpha2: 'JE',
		alpha3: 'JEY',
		numeric: 832,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Jordan',
		alpha2: 'JO',
		alpha3: 'JOR',
		numeric: 400,
		male: 74.4,
		female: 76.2,
		overall: 72.7,
	},
	{
		country: 'Kazakhstan',
		alpha2: 'KZ',
		alpha3: 'KAZ',
		numeric: 398,
		male: 76.2,
		female: 77.3,
		overall: 68.8,
	},
	{
		country: 'Kenya',
		alpha2: 'KE',
		alpha3: 'KEN',
		numeric: 404,
		male: 63.3,
		female: 68.7,
		overall: 64,
	},
	{
		country: 'Kiribati',
		alpha2: 'KI',
		alpha3: 'KIR',
		numeric: 296,
		male: 68.1,
		female: 72.1,
		overall: 64,
	},
	{
		country: 'South Korea',
		alpha2: 'KR',
		alpha3: 'KOR',
		numeric: 410,
		male: 82.8,
		female: 85.8,
		overall: 79.7,
	},
	{
		country: 'Kuwait',
		alpha2: 'KW',
		alpha3: 'KWT',
		numeric: 414,
		male: 75.4,
		female: 76.5,
		overall: 74.7,
	},
	{
		country: 'Kyrgyzstan',
		alpha2: 'KG',
		alpha3: 'KGZ',
		numeric: 417,
		male: 71.3,
		female: 75.5,
		overall: 67.3,
	},
	{
		country: 'Laos',
		alpha2: 'LA',
		alpha3: 'LAO',
		numeric: 418,
		male: 67.6,
		female: 69.4,
		overall: 65.8,
	},
	{
		country: 'Latvia',
		alpha2: 'LV',
		alpha3: 'LVA',
		numeric: 428,
		male: 75.2,
		female: 79.9,
		overall: 70.1,
	},
	{
		country: 'Lebanon',
		alpha2: 'LB',
		alpha3: 'LBN',
		numeric: 422,
		male: 78.9,
		female: 80.8,
		overall: 77.1,
	},
	{
		country: 'Lesotho',
		alpha2: 'LS',
		alpha3: 'LSO',
		numeric: 426,
		male: 53.7,
		female: 57,
		overall: 50.6,
	},
	{
		country: 'Liberia',
		alpha2: 'LR',
		alpha3: 'LBR',
		numeric: 430,
		male: 63.7,
		female: 65.1,
		overall: 62.3,
	},
	{
		country: 'Libya',
		alpha2: 'LY',
		alpha3: 'LBY',
		numeric: 434,
		male: 72.7,
		female: 75.8,
		overall: 69.9,
	},
	{
		country: 'Liechtenstein',
		alpha2: 'LI',
		alpha3: 'LIE',
		numeric: 438,
		male: 80.5,
		female: null,
		overall: null,
	},
	{
		country: 'Lithuania',
		alpha2: 'LT',
		alpha3: 'LTU',
		numeric: 440,
		male: 75.7,
		female: 81.2,
		overall: 70.1,
	},
	{
		country: 'Luxembourg',
		alpha2: 'LU',
		alpha3: 'LUX',
		numeric: 442,
		male: 82.1,
		female: 84.2,
		overall: 80,
	},
	{
		country: 'Macao',
		alpha2: 'MO',
		alpha3: 'MAC',
		numeric: 446,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Madagascar',
		alpha2: 'MG',
		alpha3: 'MDG',
		numeric: 450,
		male: 66.7,
		female: 68.3,
		overall: 65.1,
	},
	{
		country: 'Malawi',
		alpha2: 'MW',
		alpha3: 'MWI',
		numeric: 454,
		male: 63.8,
		female: 66.9,
		overall: 60.7,
	},
	{
		country: 'Malaysia',
		alpha2: 'MY',
		alpha3: 'MYS',
		numeric: 458,
		male: 76.1,
		female: 78.3,
		overall: 74.2,
	},
	{
		country: 'Maldives',
		alpha2: 'MV',
		alpha3: 'MDV',
		numeric: 462,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Mali',
		alpha2: 'ML',
		alpha3: 'MLI',
		numeric: 466,
		male: 58.9,
		female: 59.6,
		overall: 58.1,
	},
	{
		country: 'Malta',
		alpha2: 'MT',
		alpha3: 'MLT',
		numeric: 470,
		male: 82.4,
		female: 84.1,
		overall: 80.5,
	},
	{
		country: 'Marshall Islands',
		alpha2: 'MH',
		alpha3: 'MHL',
		numeric: 584,
		male: 73.9,
		female: null,
		overall: null,
	},
	{
		country: 'Martinique',
		alpha2: 'MQ',
		alpha3: 'MTQ',
		numeric: 474,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Mauritania',
		alpha2: 'MR',
		alpha3: 'MRT',
		numeric: 478,
		male: 64.7,
		female: 66.3,
		overall: 63.1,
	},
	{
		country: 'Mauritius',
		alpha2: 'MU',
		alpha3: 'MUS',
		numeric: 480,
		male: 74.9,
		female: 78.4,
		overall: 71.5,
	},
	{
		country: 'Mayotte',
		alpha2: 'YT',
		alpha3: 'MYT',
		numeric: 175,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Mexico',
		alpha2: 'MX',
		alpha3: 'MEX',
		numeric: 484,
		male: 75,
		female: 77.8,
		overall: 72.1,
	},
	{
		country: 'Micronesia',
		alpha2: 'FM',
		alpha3: 'FSM',
		numeric: 583,
		male: 67.8,
		female: 69.5,
		overall: 66.1,
	},
	{
		country: 'Moldova',
		alpha2: 'MD',
		alpha3: 'MDA',
		numeric: 498,
		male: 71.8,
		female: 76.1,
		overall: 67.5,
	},
	{
		country: 'Monaco',
		alpha2: 'MC',
		alpha3: 'MCO',
		numeric: 492,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Mongolia',
		alpha2: 'MN',
		alpha3: 'MNG',
		numeric: 496,
		male: 69.7,
		female: 74,
		overall: 65.6,
	},
	{
		country: 'Montenegro',
		alpha2: 'ME',
		alpha3: 'MNE',
		numeric: 499,
		male: 76.8,
		female: 79.2,
		overall: 74.3,
	},
	{
		country: 'Montserrat',
		alpha2: 'MS',
		alpha3: 'MSR',
		numeric: 500,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Morocco',
		alpha2: 'MA',
		alpha3: 'MAR',
		numeric: 504,
		male: 76.5,
		female: 77.7,
		overall: 75.2,
	},
	{
		country: 'Mozambique',
		alpha2: 'MZ',
		alpha3: 'MOZ',
		numeric: 508,
		male: 60.2,
		female: 63,
		overall: 57.1,
	},
	{
		country: 'Myanmar',
		alpha2: 'MM',
		alpha3: 'MMR',
		numeric: 104,
		male: 66.9,
		female: 69.9,
		overall: 63.8,
	},
	{
		country: 'Namibia',
		alpha2: 'NA',
		alpha3: 'NAM',
		numeric: 516,
		male: 63.4,
		female: 66.2,
		overall: 60.4,
	},
	{
		country: 'Nauru',
		alpha2: 'NR',
		alpha3: 'NRU',
		numeric: 520,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Nepal',
		alpha2: 'NP',
		alpha3: 'NPL',
		numeric: 524,
		male: 70.5,
		female: 71.9,
		overall: 69,
	},
	{
		country: 'Netherlands',
		alpha2: 'NL',
		alpha3: 'NLD',
		numeric: 528,
		male: 82.1,
		female: 83.8,
		overall: 80.4,
	},
	{
		country: 'New Caledonia',
		alpha2: 'NC',
		alpha3: 'NCL',
		numeric: 540,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'New Zealand',
		alpha2: 'NZ',
		alpha3: 'NZL',
		numeric: 554,
		male: 82.1,
		female: 83.9,
		overall: 80.4,
	},
	{
		country: 'Nicaragua',
		alpha2: 'NI',
		alpha3: 'NIC',
		numeric: 558,
		male: 74.3,
		female: 77.8,
		overall: 70.7,
	},
	{
		country: 'Niger',
		alpha2: 'NE',
		alpha3: 'NER',
		numeric: 562,
		male: 62,
		female: 63.2,
		overall: 60.9,
	},
	{
		country: 'Nigeria',
		alpha2: 'NG',
		alpha3: 'NGA',
		numeric: 566,
		male: 54.3,
		female: 55.2,
		overall: 53.5,
	},
	{
		country: 'Niue',
		alpha2: 'NU',
		alpha3: 'NIU',
		numeric: 570,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Norfolk Island',
		alpha2: 'NF',
		alpha3: 'NFK',
		numeric: 574,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Northern Mariana Islands',
		alpha2: 'MP',
		alpha3: 'MNP',
		numeric: 580,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Norway',
		alpha2: 'NO',
		alpha3: 'NOR',
		numeric: 578,
		male: 82.3,
		female: 84.3,
		overall: 80.3,
	},
	{
		country: 'Oman',
		alpha2: 'OM',
		alpha3: 'OMN',
		numeric: 512,
		male: 77.6,
		female: 80.1,
		overall: 75.9,
	},
	{
		country: 'Pakistan',
		alpha2: 'PK',
		alpha3: 'PAK',
		numeric: 586,
		male: 67.1,
		female: 68.1,
		overall: 66.2,
	},
	{
		country: 'Palau',
		alpha2: 'PW',
		alpha3: 'PLW',
		numeric: 585,
		male: 73.7,
		female: null,
		overall: null,
	},
	{
		country: 'Palestine',
		alpha2: 'PS',
		alpha3: 'PSE',
		numeric: 275,
		male: 73.9,
		female: 75.6,
		overall: 72.3,
	},
	{
		country: 'Panama',
		alpha2: 'PA',
		alpha3: 'PAN',
		numeric: 591,
		male: 78.3,
		female: 81.6,
		overall: 75.2,
	},
	{
		country: 'Papua New Guinea',
		alpha2: 'PG',
		alpha3: 'PNG',
		numeric: 598,
		male: 64.3,
		female: 65.6,
		overall: 63,
	},
	{
		country: 'Paraguay',
		alpha2: 'PY',
		alpha3: 'PRY',
		numeric: 600,
		male: 74.1,
		female: 76.3,
		overall: 72.2,
	},
	{
		country: 'Peru',
		alpha2: 'PE',
		alpha3: 'PER',
		numeric: 604,
		male: 76.5,
		female: 79.3,
		overall: 73.8,
	},
	{
		country: 'Philippines',
		alpha2: 'PH',
		alpha3: 'PHL',
		numeric: 608,
		male: 71.1,
		female: 75.4,
		overall: 67.1,
	},
	{
		country: 'Pitcairn',
		alpha2: 'PN',
		alpha3: 'PCN',
		numeric: 612,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Poland',
		alpha2: 'PL',
		alpha3: 'POL',
		numeric: 616,
		male: 78.5,
		female: 82.4,
		overall: 74.6,
	},
	{
		country: 'Portugal',
		alpha2: 'PT',
		alpha3: 'PRT',
		numeric: 620,
		male: 81.9,
		female: 84.7,
		overall: 78.8,
	},
	{
		country: 'Puerto Rico',
		alpha2: 'PR',
		alpha3: 'PRI',
		numeric: 630,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Qatar',
		alpha2: 'QA',
		alpha3: 'QAT',
		numeric: 634,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Republic of North Macedonia',
		alpha2: 'MK',
		alpha3: 'MKD',
		numeric: 807,
		male: 75.7,
		female: 77.7,
		overall: 73.7,
	},
	{
		country: 'Romania',
		alpha2: 'RO',
		alpha3: 'ROU',
		numeric: 642,
		male: 75.9,
		female: 79.4,
		overall: 72.5,
	},
	{
		country: 'Russian Federation',
		alpha2: 'RU',
		alpha3: 'RUS',
		numeric: 643,
		male: 72.4,
		female: 77.6,
		overall: 66.9,
	},
	{
		country: 'Rwanda',
		alpha2: 'RW',
		alpha3: 'RWA',
		numeric: 646,
		male: 68.7,
		female: 70.8,
		overall: 66.5,
	},
	{
		country: 'Réunion',
		alpha2: 'RE',
		alpha3: 'REU',
		numeric: 638,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Saint Barthélemy',
		alpha2: 'BL',
		alpha3: 'BLM',
		numeric: 652,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Saint Helena, Ascension and Tristan da Cunha',
		alpha2: 'SH',
		alpha3: 'SHN',
		numeric: 654,
		male: 81.5,
		female: 83.8,
		overall: 79.1,
	},
	{
		country: 'Saint Kitts and Nevis',
		alpha2: 'KN',
		alpha3: 'KNA',
		numeric: 659,
		male: 74.6,
		female: null,
		overall: null,
	},
	{
		country: 'Saint Lucia',
		alpha2: 'LC',
		alpha3: 'LCA',
		numeric: 662,
		male: 76.1,
		female: 77.4,
		overall: 74.7,
	},
	{
		country: 'Saint Martin',
		alpha2: 'MF',
		alpha3: 'MAF',
		numeric: 663,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Saint Pierre and Miquelon',
		alpha2: 'PM',
		alpha3: 'SPM',
		numeric: 666,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Saint Vincent and the Grenadines',
		alpha2: 'VC',
		alpha3: 'VCT',
		numeric: 670,
		male: 72.4,
		female: 75,
		overall: 70.2,
	},
	{
		country: 'Samoa',
		alpha2: 'WS',
		alpha3: 'WSM',
		numeric: 882,
		male: 73.2,
		female: 75.3,
		overall: 71.2,
	},
	{
		country: 'San Marino',
		alpha2: 'SM',
		alpha3: 'SMR',
		numeric: 674,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Sao Tome and Principe',
		alpha2: 'ST',
		alpha3: 'STP',
		numeric: 678,
		male: 70.2,
		female: 72.6,
		overall: 67.8,
	},
	{
		country: 'Saudi Arabia',
		alpha2: 'SA',
		alpha3: 'SAU',
		numeric: 682,
		male: 75,
		female: 76.6,
		overall: 73.8,
	},
	{
		country: 'Senegal',
		alpha2: 'SN',
		alpha3: 'SEN',
		numeric: 686,
		male: 67.7,
		female: 69.6,
		overall: 65.5,
	},
	{
		country: 'Serbia',
		alpha2: 'RS',
		alpha3: 'SRB',
		numeric: 688,
		male: 75.8,
		female: 78.5,
		overall: 73.3,
	},
	{
		country: 'Seychelles',
		alpha2: 'SC',
		alpha3: 'SYC',
		numeric: 690,
		male: 73.3,
		female: 77.3,
		overall: 69.8,
	},
	{
		country: 'Sierra Leone',
		alpha2: 'SL',
		alpha3: 'SLE',
		numeric: 694,
		male: 54.3,
		female: 55.1,
		overall: 53.5,
	},
	{
		country: 'Singapore',
		alpha2: 'SG',
		alpha3: 'SGP',
		numeric: 702,
		male: 83.8,
		female: 85.8,
		overall: 81.5,
	},
	{
		country: 'Sint Maarten',
		alpha2: 'SX',
		alpha3: 'SXM',
		numeric: 534,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Slovakia',
		alpha2: 'SK',
		alpha3: 'SVK',
		numeric: 703,
		male: 77.4,
		female: 80.8,
		overall: 73.8,
	},
	{
		country: 'Slovenia',
		alpha2: 'SI',
		alpha3: 'SVN',
		numeric: 705,
		male: 81.2,
		female: 83.9,
		overall: 78.4,
	},
	{
		country: 'Solomon Islands',
		alpha2: 'SB',
		alpha3: 'SLB',
		numeric: 90,
		male: 72.8,
		female: 74.7,
		overall: 71.2,
	},
	{
		country: 'Somalia',
		alpha2: 'SO',
		alpha3: 'SOM',
		numeric: 706,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'South Africa',
		alpha2: 'ZA',
		alpha3: 'ZAF',
		numeric: 710,
		male: 63.9,
		female: 67.4,
		overall: 60.5,
	},
	{
		country: 'South Georgia and the South Sandwich Islands',
		alpha2: 'GS',
		alpha3: 'SGS',
		numeric: 239,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'South Sudan',
		alpha2: 'SS',
		alpha3: 'SSD',
		numeric: 728,
		male: 57.6,
		female: 59.1,
		overall: 56.1,
	},
	{
		country: 'Spain',
		alpha2: 'ES',
		alpha3: 'ESP',
		numeric: 724,
		male: 83.4,
		female: 86.1,
		overall: 80.7,
	},
	{
		country: 'Sri Lanka',
		alpha2: 'LK',
		alpha3: 'LKA',
		numeric: 144,
		male: 76.8,
		female: 80.1,
		overall: 73.4,
	},
	{
		country: 'Sudan',
		alpha2: 'SD',
		alpha3: 'SDN',
		numeric: 729,
		male: 65.1,
		female: 66.9,
		overall: 63.3,
	},
	{
		country: 'Suriname',
		alpha2: 'SR',
		alpha3: 'SUR',
		numeric: 740,
		male: 71.6,
		female: 74.9,
		overall: 68.4,
	},
	{
		country: 'Svalbard and Jan Mayen',
		alpha2: 'SJ',
		alpha3: 'SJM',
		numeric: 744,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Sweden',
		alpha2: 'SE',
		alpha3: 'SWE',
		numeric: 752,
		male: 82.7,
		female: 84.4,
		overall: 80.9,
	},
	{
		country: 'Switzerland',
		alpha2: 'CH',
		alpha3: 'CHE',
		numeric: 756,
		male: 83.4,
		female: 85.3,
		overall: 81.1,
	},
	{
		country: 'Syria',
		alpha2: 'SY',
		alpha3: 'SYR',
		numeric: 760,
		male: 71.8,
		female: 77.8,
		overall: 66.6,
	},
	{
		country: 'Taiwan',
		alpha2: 'TW',
		alpha3: 'TWN',
		numeric: 158,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Tajikistan',
		alpha2: 'TJ',
		alpha3: 'TJK',
		numeric: 762,
		male: 70.9,
		female: 73.2,
		overall: 68.7,
	},
	{
		country: 'Tanzania',
		alpha2: 'TZ',
		alpha3: 'TZA',
		numeric: 834,
		male: 65,
		female: 66.8,
		overall: 63.2,
	},
	{
		country: 'Thailand',
		alpha2: 'TH',
		alpha3: 'THA',
		numeric: 764,
		male: 76.9,
		female: 80.7,
		overall: 73.2,
	},
	{
		country: 'Timor Leste',
		alpha2: 'TL',
		alpha3: 'TLS',
		numeric: 626,
		male: 69.3,
		female: 71.4,
		overall: 67.3,
	},
	{
		country: 'Togo',
		alpha2: 'TG',
		alpha3: 'TGO',
		numeric: 768,
		male: 60.8,
		female: 61.6,
		overall: 59.9,
	},
	{
		country: 'Tokelau',
		alpha2: 'TK',
		alpha3: 'TKL',
		numeric: 772,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Tonga',
		alpha2: 'TO',
		alpha3: 'TON',
		numeric: 776,
		male: 70.8,
		female: 72.8,
		overall: 68.9,
	},
	{
		country: 'Trinidad and Tobago',
		alpha2: 'TT',
		alpha3: 'TTO',
		numeric: 780,
		male: 73.4,
		female: 76.1,
		overall: 70.8,
	},
	{
		country: 'Tunisia',
		alpha2: 'TN',
		alpha3: 'TUN',
		numeric: 788,
		male: 76.5,
		female: 78.5,
		overall: 74.5,
	},
	{
		country: 'Turkey',
		alpha2: 'TR',
		alpha3: 'TUR',
		numeric: 792,
		male: 78.3,
		female: 81,
		overall: 75.6,
	},
	{
		country: 'Turkmenistan',
		alpha2: 'TM',
		alpha3: 'TKM',
		numeric: 795,
		male: 68.1,
		female: 71.6,
		overall: 64.6,
	},
	{
		country: 'Turks and Caicos Islands',
		alpha2: 'TC',
		alpha3: 'TCA',
		numeric: 796,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Tuvalu',
		alpha2: 'TV',
		alpha3: 'TUV',
		numeric: 798,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Uganda',
		alpha2: 'UG',
		alpha3: 'UGA',
		numeric: 800,
		male: 63,
		female: 65.2,
		overall: 60.7,
	},
	{
		country: 'Ukraine',
		alpha2: 'UA',
		alpha3: 'UKR',
		numeric: 804,
		male: 72,
		female: 76.7,
		overall: 67,
	},
	{
		country: 'United Arab Emirates',
		alpha2: 'AE',
		alpha3: 'ARE',
		numeric: 784,
		male: 77.8,
		female: 79.2,
		overall: 77.1,
	},
	{
		country: 'United Kingdom',
		alpha2: 'GB',
		alpha3: 'GBR',
		numeric: 826,
		male: 81.2,
		female: 83,
		overall: 79.5,
	},
	{
		country: 'United States Minor Outlying Islands',
		alpha2: 'UM',
		alpha3: 'UMI',
		numeric: 581,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'United States of America',
		alpha2: 'US',
		alpha3: 'USA',
		numeric: 840,
		male: 78.9,
		female: 81.4,
		overall: 76.3,
	},
	{
		country: 'Uruguay',
		alpha2: 'UY',
		alpha3: 'URY',
		numeric: 858,
		male: 77.8,
		female: 81.4,
		overall: 74,
	},
	{
		country: 'Uzbekistan',
		alpha2: 'UZ',
		alpha3: 'UZB',
		numeric: 860,
		male: 74.6,
		female: 73.7,
		overall: 69.4,
	},
	{
		country: 'Vanuatu',
		alpha2: 'VU',
		alpha3: 'VUT',
		numeric: 548,
		male: 70.3,
		female: 72,
		overall: 68.8,
	},
	{
		country: 'Venezuela',
		alpha2: 'VE',
		alpha3: 'VEN',
		numeric: 862,
		male: 72.1,
		female: 76.1,
		overall: 68.4,
	},
	{
		country: 'Vietnam',
		alpha2: 'VN',
		alpha3: 'VNM',
		numeric: 704,
		male: 75.3,
		female: 79.4,
		overall: 71.2,
	},
	{
		country: 'Virgin Islands (British)',
		alpha2: 'VG',
		alpha3: 'VGB',
		numeric: 92,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Virgin Islands (U.S.)',
		alpha2: 'VI',
		alpha3: 'VIR',
		numeric: 850,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Wallis and Futuna',
		alpha2: 'WF',
		alpha3: 'WLF',
		numeric: 876,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Western Sahara',
		alpha2: 'EH',
		alpha3: 'ESH',
		numeric: 732,
		male: null,
		female: null,
		overall: null,
	},
	{
		country: 'Yemen',
		alpha2: 'YE',
		alpha3: 'YEM',
		numeric: 887,
		male: 66.1,
		female: 67.8,
		overall: 64.4,
	},
	{
		country: 'Zambia',
		alpha2: 'ZM',
		alpha3: 'ZMB',
		numeric: 894,
		male: 63.5,
		female: 66.4,
		overall: 60.5,
	},
	{
		country: 'Zimbabwe',
		alpha2: 'ZW',
		alpha3: 'ZWE',
		numeric: 716,
		male: 61.2,
		female: 62.6,
		overall: 59.5,
	},
	{
		country: 'Åland Islands',
		alpha2: 'AX',
		alpha3: 'ALA',
		numeric: 248,
		male: null,
		female: null,
		overall: null,
	},
];
